--- !ruby/object:VR_ENV
width: 1364
height: 691
panel_pos: 270
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/examp/progressbar.rb"
- "/home/eric/vrp/examp/liststore.rb"
- "/home/eric/vrp/examp/main.rb"
- "/home/eric/vrp/examp/scalebutton.rb"
open_folders:
- "/home/eric/vrp/examp"
current_file: "/home/eric/vrp/examp/scalebutton.rb"
rdoc_command_line: rdoc -x README -x /*.glade -x /*.yaml -x /*.gemspec -x /*.css
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 474
current_line: 27
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
